color0 #1e1e2e
color1 #f38ba8
color2 #cba6f7
color3 #fab387
color4 #94e2d5
color5 #bb8af4
color6 #fab185
color7 #cdd6f4
color8 #646789
color9 #f38ba8
color10 #cba6f7
color11 #fab387
color12 #94e2d5
color13 #bb8af4
color14 #fab185
color15 #cdd6f4

cursor                #cdd6f4
cursor_text_color     #1e1e2e
background            #1e1e2e
foreground            #cdd6f4
selection_foreground  #a3b4eb
selection_background  #313244
active_border_color   #cba6f7
inactive_border_color #313244
url_color             #cba6f7

active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #a3b4eb
inactive_tab_background #313244
cursor_trail_color      #a3b4eb