[FileDialog]
history=file:///home/duzentos, file:///home/duzentos/Development/Repositories, file:///home/duzentos/Notes, file:///home/duzentos/Videos, file:///home/duzentos/Games/HydraLibrary
lastVisited=file:///home/duzentos/Games/HydraLibrary
qtVersion=6.11.0
shortcuts=file:, file:///home/duzentos
sidebarWidth=91
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
