[config]
# Aqui você pode colocar configurações globais se precisar

[templates]

[templates.kitty]
# Troque 'duzentos' pelo seu nome de usuário real no sistema
input_path = "/home/duzentos/.config/noctalia/templates/kitty-colors.conf"
output_path = "/home/duzentos/.config/kitty/colors.conf"
post_hook = "pkill -USR1 kitty"