[General]
DiskFolders=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\n\0\0\0\x1c\0/\0h\0o\0m\0\x65\0/\0\x64\0u\0z\0\x65\0n\0t\0o\0s)
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x94\0\0\0$\0\0\x6?\0\0\x3\x7f\0\0\x2\x94\0\0\0$\0\0\x6?\0\0\x3\x7f\0\0\0\0\0\0\0\0\x6@\0\0\x2\x94\0\0\0$\0\0\x6?\0\0\x3\x7f)
HorizontalScrollBarValue=1241
LastBPM=0
ShowKeyboard=true
ShowMeters=true
ShowSidePanel=true
ShowToolbar=true
VerticalScrollBarValue=872

[Engine]
TransportExtra=
TransportMode=3
